import { AccentColor, FeatureLayout } from "@prisma/client";

export const charterPageData = {
  slug: "charter",
  pageTitle: "Charter",
  heroImage: "/images/GetPaid.png",
  badgeText: "Charter Marketplace",
  heroTitle: "Search, compare, book and fly — all in one seamless charter experience.",
  heroDescription: "AvPlat Trips is designed to make charter booking simpler, faster and more transparent — from itinerary creation and instant quotes to real-time updates, flexible changes and secure payments.",
  
  stats: [
    {
      label: "30 Seconds",
      value: "Create itinerary & get quotes",
      order: 0,
    },
    {
      label: "Instant Booking",
      value: "Confirm and activate fast",
      order: 1,
    },
    {
      label: "Direct Access",
      value: "Transparent fleet pricing",
      order: 2,
    },
  ],

  features: [
    {
      order: 0,
      eyebrow: "AvPlat Trips",
      title: "Introducing AvPlat Trips: The World’s First Integrated Aircraft Charter Marketplace.",
      description: "Search aircraft, compare options, book instantly, and take off with ease. It can’t get any simpler!",
      points: [
        "Search aircraft easily",
        "Compare curated options",
        "Book instantly with confidence",
      ],
      videoId: "IlbOpSccI_E",
      icon: "Plane", 
      accent: "blue" as AccentColor,
      layout: "leftText" as FeatureLayout,
    },
    {
      order: 1,
      eyebrow: "Instant Quotes",
      title: "Create Itinerary and Get Instant Quotes!",
      description: "30 seconds is all it takes to enter your schedule, explore curated fleet and get instant charter estimates. Compare options, select the right aircraft and book when you’re ready.",
      points: [
        "Enter your schedule in seconds",
        "Explore a curated fleet",
        "Get instant charter estimates",
      ],
      videoId: "yrQKUfTskIE",
      icon: "SearchCheck",
      accent: "slate" as AccentColor,
      layout: "rightText" as FeatureLayout,
    },
    {
      order: 2,
      eyebrow: "Trip Activation",
      title: "Confirm and Activate Your Trip. Instantly!",
      description: "Once you’ve selected your aircraft, simply make the payment to confirm your booking. With one click, your trip is activated and everything is set in motion. Sit back and relax as your journey is seamlessly managed from start to finish.",
      points: [
        "Confirm booking with payment",
        "Activate the trip with one click",
        "End-to-end journey coordination",
      ],
      videoId: "IlbOpSccI_E",
      icon: "BadgeCheck",
      accent: "blue" as AccentColor,
      layout: "centerSplit" as FeatureLayout,
    },
    {
      order: 3,
      eyebrow: "World-Class Fleet",
      title: "Direct Access to a World-Class Fleet.",
      description: "Explore a diverse fleet and select the perfect aircraft for your mission. With direct access to operators, avoid layers of intermediaries, reduce brokerage costs and enjoy complete pricing transparency.",
      points: [
        "Explore a diverse fleet",
        "Direct access to operators",
        "Transparent pricing with lower brokerage costs",
      ],
      videoId: "yrQKUfTskIE",
      icon: "Globe2",
      accent: "slate" as AccentColor,
      layout: "leftText" as FeatureLayout,
    },
    {
      order: 4,
      eyebrow: "Live Updates",
      title: "Stay Updated. Every Step of the Way!",
      description: "Get real-time updates, alerts and notifications throughout your journey. Trip updates and seamless communication ensure you stay on top of every detail from start to finish.",
      points: [
        "Real-time alerts and notifications",
        "Stay informed throughout the trip",
        "Seamless communication end to end",
      ],
      videoId: "IlbOpSccI_E",
      icon: "BellRing",
      accent: "blue" as AccentColor,
      layout: "rightText" as FeatureLayout,
    },
    {
      order: 5,
      eyebrow: "Flexible Planning",
      title: "Change Plans. Effortlessly!",
      description: "Modify your itinerary, passengers or schedule anytime. The platform automatically updates and informs everyone involved, keeping your trip smooth and stress-free.",
      points: [
        "Change itinerary anytime",
        "Update passengers and schedule easily",
        "Automatic coordination for everyone involved",
      ],
      videoId: "yrQKUfTskIE",
      icon: "RefreshCcw",
      accent: "slate" as AccentColor,
      layout: "centerSplit" as FeatureLayout,
    },
    {
      order: 6,
      eyebrow: "Flexible Payments",
      title: "Flexible Payments. Seamless Experience.",
      description: "Pay using credit cards and a range of convenient options. Fast, secure and designed to fit your preferences—every time.",
      points: [
        "Credit card support",
        "Convenient payment options",
        "Fast and secure checkout experience",
      ],
      videoId: "IlbOpSccI_E",
      icon: "CreditCard",
      accent: "blue" as AccentColor,
      layout: "leftText" as FeatureLayout,
    },
  ],
};